repos:
  - repo: https://github.com/pierre-sassoulas/setup-cfg-fmt
    rev: 7e3f370a888236fe516749432f2cf5daadf31f89
    hooks:
      - id: setup-cfg-fmt
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.12.0
    hooks:
      - id: pyupgrade
        exclude: tests/testdata
        args: [--py36-plus]
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        args: [--safe, --quiet]
        exclude: tests/testdata|doc/
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        exclude: .github/|tests/testdata
      - id: end-of-file-fixer
        exclude: tests/testdata
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        args: [--prose-wrap=always, --print-width=88]
